# Generated by Django 4.2.4 on 2023-08-13 16:07

import ajaxapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxapp', '0002_alter_sample_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=30, validators=[ajaxapp.models.Sample.name_check, ajaxapp.models.Sample.name_check_len]),
        ),
    ]
